# Generated by Django 5.2.6 on 2025-10-01 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('phone', models.CharField(blank=True, max_length=50, null=True)),
                ('date', models.CharField(blank=True, max_length=100, null=True)),
                ('model', models.CharField(blank=True, max_length=255, null=True)),
                ('gar1', models.CharField(blank=True, max_length=255, null=True)),
                ('gar2', models.CharField(blank=True, max_length=255, null=True)),
                ('price', models.CharField(blank=True, max_length=50, null=True)),
                ('lens', models.CharField(blank=True, max_length=255, null=True)),
                ('ax', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'Девайс',
                'verbose_name_plural': 'Девайсы',
            },
        ),
    ]
