# Generated by Django 5.2.6 on 2025-10-04 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_used', models.BooleanField(default=False, verbose_name='Просрочка')),
                ('where', models.CharField(blank=True, choices=[('ЦУМ', 'ЦУМ'), ('ГУМ', 'ГУМ')], max_length=5, null=True, verbose_name='где')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='ФИО')),
                ('phone', models.CharField(blank=True, max_length=255, null=True, verbose_name='Телефон')),
                ('date', models.DateTimeField(blank=True, null=True, verbose_name='Дата')),
                ('model', models.CharField(blank=True, max_length=255, null=True, verbose_name='Модель')),
                ('price', models.CharField(blank=True, max_length=255, null=True, verbose_name='Цена')),
                ('display', models.BooleanField(default=False, verbose_name='Экран')),
                ('case', models.BooleanField(default=False, verbose_name='Корпус')),
                ('general_360', models.BooleanField(default=False, verbose_name='360')),
                ('side', models.BooleanField(default=False, verbose_name='Бокавая часть')),
                ('lens', models.BooleanField(default=False, verbose_name='Линзы')),
                ('created_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата создание')),
            ],
            options={
                'verbose_name': 'Девайс',
                'verbose_name_plural': 'Девайсы',
            },
        ),
    ]
