# Generated by Django 5.2.6 on 2025-10-01 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='where',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
