# Generated by Django 5.2.6 on 2025-10-04 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_device_where'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='ax',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Ax'),
        ),
        migrations.AlterField(
            model_name='device',
            name='date',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='device',
            name='gar1',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Гар 1'),
        ),
        migrations.AlterField(
            model_name='device',
            name='gar2',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Гар 2'),
        ),
        migrations.AlterField(
            model_name='device',
            name='lens',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Линзы'),
        ),
        migrations.AlterField(
            model_name='device',
            name='model',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Модель'),
        ),
        migrations.AlterField(
            model_name='device',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='device',
            name='phone',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='device',
            name='price',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='device',
            name='where',
            field=models.CharField(blank=True, choices=[('ЦУМ', 'ЦУМ'), ('ГУМ', 'ГУМ')], max_length=5, null=True, verbose_name='где'),
        ),
    ]
