# Generated by Django 5.2.6 on 2025-10-05 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_device_created_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='device',
            options={'verbose_name': 'Клиента', 'verbose_name_plural': 'Клиенты'},
        ),
        migrations.AddField(
            model_name='device',
            name='cover',
            field=models.BooleanField(default=False, verbose_name='Крышка'),
        ),
    ]
