# Generated by Django 5.2.6 on 2025-10-05 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_device_options_device_cover'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='case_date',
            field=models.DateField(blank=True, null=True, verbose_name='Гарантия корпуса до'),
        ),
        migrations.AddField(
            model_name='device',
            name='cover_date',
            field=models.DateField(blank=True, null=True, verbose_name='Гарантия крышки до'),
        ),
        migrations.AddField(
            model_name='device',
            name='display_date',
            field=models.DateField(blank=True, null=True, verbose_name='Гарантия экрана до'),
        ),
        migrations.AddField(
            model_name='device',
            name='general_360_date',
            field=models.DateField(blank=True, null=True, verbose_name='Гарантия 360 до'),
        ),
        migrations.AddField(
            model_name='device',
            name='side_date',
            field=models.DateField(blank=True, null=True, verbose_name='Гарантия боковой части до'),
        ),
        migrations.AlterField(
            model_name='device',
            name='is_used',
            field=models.BooleanField(default=False, verbose_name='Просрочка/ИСП'),
        ),
    ]
