# Generated by Django 5.2.6 on 2025-10-04 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_device_ax_alter_device_date_alter_device_gar1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='is_used',
            field=models.CharField(blank=True, choices=[('ЦУМ', 'ЦУМ'), ('ГУМ', 'ГУМ')], max_length=255, null=True, verbose_name='Статус гарантии'),
        ),
    ]
