# Generated by Django 5.2.6 on 2025-10-05 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_device_case_date_device_cover_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='lens_date',
            field=models.DateField(blank=True, editable=False, null=True, verbose_name='Гарантия линзы до'),
        ),
        migrations.AlterField(
            model_name='device',
            name='case_date',
            field=models.DateField(blank=True, editable=False, null=True, verbose_name='Гарантия корпуса до'),
        ),
        migrations.AlterField(
            model_name='device',
            name='cover_date',
            field=models.DateField(blank=True, editable=False, null=True, verbose_name='Гарантия крышки до'),
        ),
        migrations.AlterField(
            model_name='device',
            name='display_date',
            field=models.DateField(blank=True, editable=False, null=True, verbose_name='Гарантия экрана до'),
        ),
        migrations.AlterField(
            model_name='device',
            name='general_360_date',
            field=models.DateField(blank=True, editable=False, null=True, verbose_name='Гарантия 360 до'),
        ),
        migrations.AlterField(
            model_name='device',
            name='side_date',
            field=models.DateField(blank=True, editable=False, null=True, verbose_name='Гарантия боковой части до'),
        ),
    ]
