# Generated by Django 5.2.6 on 2025-10-06 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_device_lens_date_alter_device_case_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='is_used_date',
            field=models.DateField(blank=True, null=True, verbose_name='Использовано в'),
        ),
        migrations.AlterField(
            model_name='device',
            name='case_date',
            field=models.DateField(blank=True, null=True, verbose_name='Гарантия корпуса'),
        ),
        migrations.AlterField(
            model_name='device',
            name='cover_date',
            field=models.DateField(blank=True, null=True, verbose_name='Гарантия крышки'),
        ),
        migrations.AlterField(
            model_name='device',
            name='display_date',
            field=models.DateField(blank=True, null=True, verbose_name='Гарантия экрана'),
        ),
        migrations.AlterField(
            model_name='device',
            name='general_360_date',
            field=models.DateField(blank=True, null=True, verbose_name='Гарантия 360'),
        ),
        migrations.AlterField(
            model_name='device',
            name='lens_date',
            field=models.DateField(blank=True, null=True, verbose_name='Гарантия линзы'),
        ),
        migrations.AlterField(
            model_name='device',
            name='side_date',
            field=models.DateField(blank=True, null=True, verbose_name='Гарантия боковой части'),
        ),
    ]
