# Generated by Django 5.2.6 on 2025-10-04 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_device_is_used'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='is_used',
            field=models.BooleanField(null=True, verbose_name='Использовано'),
        ),
    ]
