# Generated by Django 5.2.6 on 2025-10-04 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_device_is_used'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='gar1',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Экран'),
        ),
        migrations.AlterField(
            model_name='device',
            name='gar2',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Корпус'),
        ),
    ]
