# Generated by Django 5.2.6 on 2025-10-06 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_device_is_used_date_alter_device_case_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='device',
            name='is_used_date',
        ),
    ]
