# Generated by Django 5.2.6 on 2025-10-06 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_remove_device_is_used_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='device',
            options={'verbose_name': 'Клиент', 'verbose_name_plural': 'Клиенты'},
        ),
        migrations.AddField(
            model_name='device',
            name='case_warranty',
            field=models.BooleanField(default=False, verbose_name='Гарантия корпуса'),
        ),
        migrations.AddField(
            model_name='device',
            name='cover_warranty',
            field=models.BooleanField(default=False, verbose_name='Гарантия крышки'),
        ),
        migrations.AddField(
            model_name='device',
            name='display_warranty',
            field=models.BooleanField(default=False, verbose_name='Гарантия экрана'),
        ),
        migrations.AddField(
            model_name='device',
            name='general_360_warranty',
            field=models.BooleanField(default=False, verbose_name='Гарантия 360'),
        ),
        migrations.AddField(
            model_name='device',
            name='lens_warranty',
            field=models.BooleanField(default=False, verbose_name='Гарантия линзы'),
        ),
        migrations.AddField(
            model_name='device',
            name='side_warranty',
            field=models.BooleanField(default=False, verbose_name='Гарантия боковой части'),
        ),
        migrations.AddField(
            model_name='device',
            name='used_case_date',
            field=models.DateField(blank=True, null=True, verbose_name='Использовано корпус'),
        ),
        migrations.AddField(
            model_name='device',
            name='used_cover_date',
            field=models.DateField(blank=True, null=True, verbose_name='Использовано крышка'),
        ),
        migrations.AddField(
            model_name='device',
            name='used_display_date',
            field=models.DateField(blank=True, null=True, verbose_name='Использовано экран'),
        ),
        migrations.AddField(
            model_name='device',
            name='used_general_360_date',
            field=models.DateField(blank=True, null=True, verbose_name='Использовано 360'),
        ),
        migrations.AddField(
            model_name='device',
            name='used_lens_date',
            field=models.DateField(blank=True, null=True, verbose_name='Использовано линзы'),
        ),
        migrations.AddField(
            model_name='device',
            name='used_side_date',
            field=models.DateField(blank=True, null=True, verbose_name='Использовано боковая часть'),
        ),
        migrations.AlterField(
            model_name='device',
            name='case_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата гарантии корпуса'),
        ),
        migrations.AlterField(
            model_name='device',
            name='cover_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата гарантии крышки'),
        ),
        migrations.AlterField(
            model_name='device',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='device',
            name='display_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата гарантии экрана'),
        ),
        migrations.AlterField(
            model_name='device',
            name='general_360_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата гарантии 360'),
        ),
        migrations.AlterField(
            model_name='device',
            name='lens_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата гарантии линзы'),
        ),
        migrations.AlterField(
            model_name='device',
            name='side',
            field=models.BooleanField(default=False, verbose_name='Боковая часть'),
        ),
        migrations.AlterField(
            model_name='device',
            name='side_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата гарантии боковой части'),
        ),
    ]
