# Generated by Django 5.2.6 on 2025-10-04 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_device_gar1_alter_device_gar2'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='side',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Бокавая часть'),
        ),
    ]
