# Generated by Django 5.2.6 on 2025-10-08 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_device_options_device_case_warranty_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='device',
            name='case',
        ),
        migrations.RemoveField(
            model_name='device',
            name='case_date',
        ),
        migrations.RemoveField(
            model_name='device',
            name='case_warranty',
        ),
        migrations.RemoveField(
            model_name='device',
            name='cover',
        ),
        migrations.RemoveField(
            model_name='device',
            name='cover_date',
        ),
        migrations.RemoveField(
            model_name='device',
            name='cover_warranty',
        ),
        migrations.RemoveField(
            model_name='device',
            name='display',
        ),
        migrations.RemoveField(
            model_name='device',
            name='display_date',
        ),
        migrations.RemoveField(
            model_name='device',
            name='display_warranty',
        ),
        migrations.RemoveField(
            model_name='device',
            name='general_360',
        ),
        migrations.RemoveField(
            model_name='device',
            name='general_360_date',
        ),
        migrations.RemoveField(
            model_name='device',
            name='general_360_warranty',
        ),
        migrations.RemoveField(
            model_name='device',
            name='lens',
        ),
        migrations.RemoveField(
            model_name='device',
            name='lens_date',
        ),
        migrations.RemoveField(
            model_name='device',
            name='lens_warranty',
        ),
        migrations.RemoveField(
            model_name='device',
            name='side',
        ),
        migrations.RemoveField(
            model_name='device',
            name='side_date',
        ),
        migrations.RemoveField(
            model_name='device',
            name='side_warranty',
        ),
        migrations.RemoveField(
            model_name='device',
            name='used_case_date',
        ),
        migrations.RemoveField(
            model_name='device',
            name='used_cover_date',
        ),
        migrations.RemoveField(
            model_name='device',
            name='used_display_date',
        ),
        migrations.RemoveField(
            model_name='device',
            name='used_general_360_date',
        ),
        migrations.RemoveField(
            model_name='device',
            name='used_lens_date',
        ),
        migrations.RemoveField(
            model_name='device',
            name='used_side_date',
        ),
        migrations.AddField(
            model_name='device',
            name='case_status',
            field=models.CharField(choices=[('not_changed', '❌ Не менялось'), ('with_warranty', '✅ Заменено (гарантия)'), ('warranty_used', '⚠️ Гарантия использована'), ('without_warranty', '🔧 Без гарантии')], default='not_changed', max_length=20, verbose_name='Корпус'),
        ),
        migrations.AddField(
            model_name='device',
            name='case_used_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата использования гарантии'),
        ),
        migrations.AddField(
            model_name='device',
            name='case_warranty_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата окончания гарантии'),
        ),
        migrations.AddField(
            model_name='device',
            name='cover_status',
            field=models.CharField(choices=[('not_changed', '❌ Не менялось'), ('with_warranty', '✅ Заменено (гарантия)'), ('warranty_used', '⚠️ Гарантия использована'), ('without_warranty', '🔧 Без гарантии')], default='not_changed', max_length=20, verbose_name='Крышка'),
        ),
        migrations.AddField(
            model_name='device',
            name='cover_used_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата использования гарантии'),
        ),
        migrations.AddField(
            model_name='device',
            name='cover_warranty_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата окончания гарантии'),
        ),
        migrations.AddField(
            model_name='device',
            name='display_status',
            field=models.CharField(choices=[('not_changed', '❌ Не менялось'), ('with_warranty', '✅ Заменено (гарантия)'), ('warranty_used', '⚠️ Гарантия использована'), ('without_warranty', '🔧 Без гарантии')], default='not_changed', max_length=20, verbose_name='Экран'),
        ),
        migrations.AddField(
            model_name='device',
            name='display_used_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата использования гарантии'),
        ),
        migrations.AddField(
            model_name='device',
            name='display_warranty_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата окончания гарантии'),
        ),
        migrations.AddField(
            model_name='device',
            name='general_360_status',
            field=models.CharField(choices=[('not_changed', '❌ Не менялось'), ('with_warranty', '✅ Заменено (гарантия)'), ('warranty_used', '⚠️ Гарантия использована'), ('without_warranty', '🔧 Без гарантии')], default='not_changed', max_length=20, verbose_name='360 (полная оклейка)'),
        ),
        migrations.AddField(
            model_name='device',
            name='general_360_used_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата использования гарантии'),
        ),
        migrations.AddField(
            model_name='device',
            name='general_360_warranty_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата окончания гарантии'),
        ),
        migrations.AddField(
            model_name='device',
            name='lens_status',
            field=models.CharField(choices=[('not_changed', '❌ Не менялось'), ('with_warranty', '✅ Заменено (гарантия)'), ('warranty_used', '⚠️ Гарантия использована'), ('without_warranty', '🔧 Без гарантии')], default='not_changed', max_length=20, verbose_name='Линзы'),
        ),
        migrations.AddField(
            model_name='device',
            name='lens_used_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата использования гарантии'),
        ),
        migrations.AddField(
            model_name='device',
            name='lens_warranty_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата окончания гарантии'),
        ),
        migrations.AddField(
            model_name='device',
            name='side_status',
            field=models.CharField(choices=[('not_changed', '❌ Не менялось'), ('with_warranty', '✅ Заменено (гарантия)'), ('warranty_used', '⚠️ Гарантия использована'), ('without_warranty', '🔧 Без гарантии')], default='not_changed', max_length=20, verbose_name='Боковая часть'),
        ),
        migrations.AddField(
            model_name='device',
            name='side_used_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата использования гарантии'),
        ),
        migrations.AddField(
            model_name='device',
            name='side_warranty_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата окончания гарантии'),
        ),
    ]
