# Generated by Django 5.2.6 on 2025-10-04 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_device_side'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='general_360',
            field=models.BooleanField(blank=True, null=True, verbose_name='360'),
        ),
    ]
