# Generated by Django 5.2.6 on 2025-10-04 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_device_general_360'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='device',
            name='ax',
        ),
    ]
