# Generated by Django 5.2.6 on 2025-10-04 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_device_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='created_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата создание'),
        ),
    ]
