# Generated by Django 5.2.6 on 2025-10-04 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_alter_device_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='gar1',
            field=models.BooleanField(default=False, verbose_name='Экран'),
        ),
        migrations.AlterField(
            model_name='device',
            name='gar2',
            field=models.BooleanField(default=True, verbose_name='Корпус'),
        ),
        migrations.AlterField(
            model_name='device',
            name='lens',
            field=models.BooleanField(default=False, verbose_name='Линзы'),
        ),
        migrations.AlterField(
            model_name='device',
            name='side',
            field=models.BooleanField(default=True, verbose_name='Бокавая часть'),
        ),
    ]
