# Generated by Django 5.2.6 on 2025-10-04 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_alter_device_gar1_alter_device_gar2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='gar2',
            field=models.BooleanField(default=False, verbose_name='Корпус'),
        ),
        migrations.AlterField(
            model_name='device',
            name='general_360',
            field=models.BooleanField(default=True, verbose_name='360'),
        ),
        migrations.AlterField(
            model_name='device',
            name='is_used',
            field=models.BooleanField(default=False, verbose_name='Использовано'),
        ),
        migrations.AlterField(
            model_name='device',
            name='lens',
            field=models.BooleanField(default=True, verbose_name='Линзы'),
        ),
    ]
